### PR TITLE
Recursive DFS -> DFS with stack

### PR DESCRIPTION
**Pull request by aobolensk**
There was a problem with recursive DFS: GPA algorithm produced segmentation fault on large graphs.

### CODE REVIEW

**Comment by allnes** [comment]
how many time algorithm speed up after change

**Comment by aobolensk** [comment]
I didn't measure time, but GPA doesn't produce seg. fault in case of large graphs anymore

**Comment by aobolensk** [comment]
DFS is used only in GPA (among matching algorithms)

**Comment by allnes** [comment]
and if tests will become slowly

**Comment by allnes** [comment]
need to look at benchmark tests after and before changes

**Comment by allnes** [comment]
i waiting results

**Comment by aobolensk** [comment]
I performed some tests:
zadeh_test n=300
GPA + random
before (recursive): 0:43
after (stack): 1:05
It became slower, but benchmark time became way more slower (more than 5 times).

**Comment by aobolensk** [comment]
On CI machine it's getting slower in times.
image
image

**Comment by allnes** [comment]
> On CI machine it's getting slower in times.
> image
> image

it's badly, i think that need at will be analyze time work of algorithm and remove excess operations and data structure.

**Review by allnes — APPROVED** [review]

**Pull request merged**
